PREFIX ny: <http://asu.edu/semantics/crime#>

SELECT ?id ?date ?lat ?lon ?borough
WHERE {
  ?e a ny:CrimeEvent ;
     ny:incidentId ?id ;
     ny:occurrenceDate ?date ;
     ny:occurredAt ?loc .
  ?loc ny:latitude ?lat ;
       ny:longitude ?lon .

  ##BOROUGH_FILTER##
  OPTIONAL {
    ?loc ny:inBorough ?b .
    ?b ny:name ?borough .
  }
}
ORDER BY DESC(?date)
LIMIT 500
